name = "zola.386"
description = "Zola port of the BOOTSTRA.386 theme."
license = "MIT"
homepage = "https://github.com/lopes/zola.386"
min_version = "0.10.1"
demo = "https://zola386.netlify.com"

[author]
name = "Jos√© Lopes"
homepage = "https://github.com/lopes"
